---
title: Life.inspect
timezone: Asia/Singapore
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'www.lifeinspect.com | Life • Inspected by Shinn Chong

'
baseurl: ''
url: https://www.lifeinspect.com
twitter_username: shinnchong
github_username: shinnyx
paginate: 20
paginate_path: "/page/:num/"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
